### ISSUE TITLE
Add form validation and allow empty fields

### ISSUE THREAD

**Issue by siliconion** [wwcodeatx/lightning_talk#9]
Currently if twitter handle is empty, the API call will fail.
After https://github.com/wwcodeatx/lightning_talk/issues/8, we should have form validation and not call API if mandatory fields(talk title and presenter name) are empty. For non-mandatory fields, do not send them to the backend. (not sure if this is the right way to deal with empty fields, please comment below)

**Comment by ceci21** [comment]
What do you mean by "For non-mandatory fields, do not send them to the backend"?

**Comment by sydbails** [comment]
Hey girl hey! Super excited to help contribute on your project. Ensuring that a form has mandatory fields is definitely reasonable and makes sense. I am curious about the other part re: "do not send them to the backend."

What I think you mean is that this information is not necessary to send a POST request to your database and should be allowed to be left blank. If this is the case, do you want the mandatory behavior to default all empty fields to an empty string and send those to your backend, which can be changed via a PATCH request in the future? Or do you not want those fields to be sent in at all? Let me know -- look forward to helping out!

Syd

**Comment by siliconion** [comment]
Thanks for your interests!  
I was thinking, for mandatory fields, the front end should make sure they exists. For optional fields, if the user enters it, send them to back end. If the user leaves them empty, completely omit the field in the POST call. I think this is probably easier to handle in the backend. What do you think? Is this reasonable?
